export const NOTIFICATION_TYPE = {
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_REPLIED: 'TICKET_REPLIED',
  TICKET_STATUS_CHANGED: 'TICKET_STATUS_CHANGED',
  SYSTEM: 'SYSTEM'
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];
